import type { StoreProduct } from "@/lib/catalog";

export const modernAllImages = [
  "/campaign/modernAll/DSCF0093.JPG",
  "/campaign/modernAll/DSCF0127.JPG",
  "/campaign/modernAll/DSCF0181.JPG",
  "/campaign/modernAll/DSCF0280.JPG",
  "/campaign/modernAll/DSCF0415.JPG",
  "/campaign/modernAll/DSCF0422.JPG",
  "/campaign/modernAll/DSCF0479.JPG",
  "/campaign/modernAll/DSCF0544.JPG",
  "/campaign/modernAll/DSCF9999.JPG",
] as const;

export const campaignProducts = [
  {
    folder: "hat",
    name: "Vision EB Hat",
    nameHe: "כובע Vision EB",
    slug: "vision-logo-beanie",
    description: "A fitted streetwear beanie finished with the sculpted EYEBREED monogram. Designed to frame the face and complete the Vision uniform.",
    descriptionHe: "כובע רחוב בגזרה מדויקת עם מונוגרמת EYEBREED. נועד למסגר את הפנים ולהשלים את מראה Vision.",
    story: "The smallest piece in the collection carries its clearest signature: a repeated monogram drawn from the idea of seeing differently.",
    storyHe: "הפריט הקטן בקולקציה נושא את החתימה הברורה ביותר שלה — מונוגרמה שחוזרת לרעיון של מבט אחר.",
    material: "Soft rib-knit cotton blend",
    prices: { USD: 45, ILS: 169, EUR: 42 },
    sizes: ["ONE SIZE"],
    displayImage: "/campaign/hat/display.JPG",
    images: [
      "/campaign/hat/model_View.jpg",
      "/campaign/hat/display.JPG",
      "/campaign/hat/DSCF9877.JPG",
      "/campaign/hat/DSCF0133.JPG",
      "/campaign/hat/DSCF0139.JPG",
      "/campaign/hat/DSCF0144.JPG",
    ],
  },
  {
    folder: "hoodie",
    name: "Vision Zip Up",
    nameHe: "קפוצ׳ון Vision Zip Up",
    slug: "vision-washed-zip-hoodie",
    description: "An oversized zip hoodie with a washed charcoal finish, dimensional Vision script and embroidered EYEBREED details across the hood and cuffs.",
    descriptionHe: "קפוצ׳ון רוכסן אוברסייז בגימור פחם שטוף, כיתוב Vision בולט ורקמות EYEBREED על הכובע והשרוולים.",
    story: "Washed to feel lived-in from the first wear, this hoodie brings together hand-drawn lettering, utility construction and a relaxed unisex silhouette.",
    storyHe: "שטיפה שמעניקה תחושת וינטג׳ כבר מהלבישה הראשונה, בשילוב כתב יד, בנייה שימושית וגזרת יוניסקס משוחררת.",
    material: "Heavyweight washed cotton fleece",
    prices: { USD: 129, ILS: 479, EUR: 119 },
    sizes: ["XS", "S", "M", "L", "XL"],
    displayImage: "/campaign/hoodie/display.JPG",
    images: [
      "/campaign/hoodie/model_View.jpg",
      "/campaign/hoodie/display.JPG",
      "/campaign/hoodie/DSCF9961.JPG",
      "/campaign/hoodie/DSCF9999.JPG",
      "/campaign/hoodie/DSCF0035.JPG",
      "/campaign/hoodie/DSCF0042.JPG",
      "/campaign/hoodie/DSCF0436.JPG",
      "/campaign/hoodie/DSCF0446.JPG",
      "/campaign/hoodie/DSCF0479.JPG",
      "/campaign/hoodie/DSCF0588.JPG",
      "/campaign/hoodie/DSCF0600.JPG",
      "/campaign/hoodie/DSCF9919.JPG",
      "/campaign/hoodie/DSCF9933.JPG",
      "/campaign/hoodie/DSCF9938.JPG",
    ],
  },
  {
    folder: "pants",
    name: "Vision Joggers",
    nameHe: "מכנסי Vision Joggers",
    slug: "vision-panel-sweatpants",
    description: "Wide-leg grey sweatpants with a contrast side panel, relaxed drop and embroidered EYEBREED emblem near the hem.",
    descriptionHe: "מכנסי טרנינג אפורים ורחבים עם פס צד מנוגד, נפילה משוחררת וסמל EYEBREED רקום ליד המכפלת.",
    story: "Built for movement, the exaggerated leg and graphic panel turn a familiar sportswear shape into a strong everyday statement.",
    storyHe: "הגזרה הרחבה והפס הגרפי הופכים צללית ספורטיבית מוכרת לפריט יומיומי עם נוכחות.",
    material: "Brushed heavyweight cotton",
    prices: { USD: 99, ILS: 369, EUR: 92 },
    sizes: ["XS", "S", "M", "L", "XL"],
    displayImage: "/campaign/pants/display.JPG",
    images: [
      "/campaign/pants/model_View.jpg",
      "/campaign/pants/display.JPG",
      "/campaign/pants/DSCF0068.JPG",
      "/campaign/pants/DSCF0501.JPG",
      "/campaign/pants/DSCF0102.JPG",
      "/campaign/pants/DSCF0125.JPG",
      "/campaign/pants/DSCF0519.JPG",
      "/campaign/pants/DSCF0520.JPG",
      "/campaign/pants/DSCF0538.JPG",
      "/campaign/pants/DSCF0544.JPG",
      "/campaign/pants/DSCF0565.JPG",
    ],
  },
  {
    folder: "shirt",
    name: "Vision Polo",
    nameHe: "חולצת Vision Polo",
    slug: "vision-25-layered-jersey",
    description: "A relaxed brown jersey layered over contrast white sleeves, finished with collegiate marks and the oversized Vision 25 back graphic.",
    descriptionHe: "חולצת ג׳רזי חומה בגזרה משוחררת מעל שרוולים לבנים, עם סמלים קולג׳יאליים והדפס Vision 25 גדול בגב.",
    story: "The number 25 marks the collection year. Sport references and handwritten graphics meet in a piece designed for layering and community.",
    storyHe: "המספר 25 מציין את שנת הקולקציה. השראות ספורט וגרפיקה ידנית נפגשות בפריט שנועד לשכבות ולקהילה.",
    material: "Midweight cotton jersey",
    prices: { USD: 89, ILS: 329, EUR: 82 },
    sizes: ["XS", "S", "M", "L", "XL"],
    displayImage: "/campaign/shirt/display.JPG",
    images: [
      "/campaign/shirt/model_View.jpg",
      "/campaign/shirt/display.JPG",
      "/campaign/shirt/DSCF0054.JPG",
      "/campaign/shirt/DSCF0177.JPG",
      "/campaign/shirt/DSCF0090.JPG",
      "/campaign/shirt/DSCF0093.JPG",
      "/campaign/shirt/DSCF0111.JPG",
      "/campaign/shirt/DSCF0134.JPG",
      "/campaign/shirt/DSCF0181.JPG",
      "/campaign/shirt/DSCF0221.JPG",
      "/campaign/shirt/DSCF0246.JPG",
      "/campaign/shirt/DSCF0256.JPG",
      "/campaign/shirt/DSCF0280.JPG",
      "/campaign/shirt/DSCF0300.JPG",
      "/campaign/shirt/DSCF0303.JPG",
    ],
  },
] as const;

export function campaignProductToStoreProduct(
  item: (typeof campaignProducts)[number],
  databaseProduct?: StoreProduct,
): StoreProduct {
  const perSize = item.folder === "hat" ? 30 : 6;
  return {
    id: databaseProduct?.id ?? `campaign-${item.slug}`,
    slug: item.slug,
    name: item.name,
    nameHe: item.nameHe,
    material: item.material,
    image: item.displayImage,
    images: [...item.images],
    description: item.description,
    descriptionHe: item.descriptionHe,
    story: item.story,
    storyHe: item.storyHe,
    inventory: databaseProduct?.inventory ?? perSize * item.sizes.length,
    sizes: databaseProduct?.sizes ?? item.sizes.map((size) => ({ size, inventory: perSize })),
    prices: { ...item.prices },
  };
}
